### ISSUE TITLE
Use MinProtocol TLSv1.2

### ISSUE THREAD

**Issue by AxelNennker** [Governikus/AusweisApp2-Omapi#1]
AusweisApp2 uses the Qt5 network module.

That module allows to set backend options.
https://doc.qt.io/qt-5/qsslconfiguration.html#setBackendConfigurationOption

One of the options is MinProtocol and the values are listed here:
https://www.openssl.org/docs/manmaster/man3/SSL_CONF_cmd.html#SUPPORTED-CONFIGURATION-FILE-COMMANDS

Currently supported protocol values are SSLv3, TLSv1, TLSv1.1, TLSv1.2, TLSv1.3, DTLSv1 and DTLSv1.2

I think that AusweisApp2 should not support any protocol below TLSv1.2.

AA2 should set the MinProtocol backend option to TLSv1.2

**Comment by misery** [comment]
Thanks, for information. This issue tracker is not used as it is for an experimental version of OMAPI. This is not the official AusweisApp2!

Also the AusweisApp2 already uses TLS 1.2 only.
